### ISSUE TITLE
CUST_KEEP_DEAD_ENEMIES

### ISSUE THREAD

**Issue by AkyV** [TokyoSU/Plugin_TokyoSU#13]
Previously there was a bug that if I save the game while the dead body is still disappearing, and then  I load that game, then the body will be restored forever in full opaque.
It is fixed now, but there is another issue (tested with TR2 Flamethrower): Customize= CUST_KEEP_DEAD_ENEMIES doesn't work for plugin creatures (but works for TRLE ones), the dead body will disappear by degrees, as if that script command weren't set.

**Comment by TokyoSU** [comment]
what entity have you tested when you use this command ?
with the BIRD_MONSTER, it not disappear with this command.

**Comment by AkyV** [comment]
TR2 Flamethrower

**Comment by TokyoSU** [comment]
i will look at it tomorrow.

**Comment by AkyV** [comment]
I think it was only a bad scripting on my side. It works now!

**Comment by TokyoSU** [comment]
if it work i can close it now, if you found another problem with this command and it's related to my plugin, you are free to open it anytime.

**Comment by AkyV** [comment]
Okay. :)
