### ISSUE TITLE
Rig worker low shotgun hit rate

### ISSUE THREAD

**Issue by AkyV** [TokyoSU/Plugin_TokyoSU#32]
Once I told if the worker moves with the shotgun (not true if he shoots at Lara on his knee!), then some shots won't hurt Lara at all.
Then you answered this:
"The shotgun shoot 6 bullet instead of 1, unlike the TR2 one, but probably a wrong value at checking range :x"

**Comment by TokyoSU** [comment]
or it can be the walk shot that have a problem.
