### ISSUE TITLE
Dog cannot pass from one level of slope

### ISSUE THREAD

**Issue by AdoCroft111** [TokyoSU/Plugin_TokyoSU#43]
Hi, there is another problem. Today I tested dog behavior in TR2 custom level, where i tried to test passing dog over a one level up/down slope and i found out that dog can pass from that, but in your version of dog behavior it doesn't pass over that.

Here is a video:
https://youtu.be/od59MV7fK1Q

**Comment by LaraHCroft91** [comment]
He also can't pass 1/4 height.

**Comment by TokyoSU** [comment]
i dont know what it cause this :x it's the code from TR3 that are the same as TR2.
