### ISSUE TITLE
[BUG] GOON_STICK: turning torso up and down

### ISSUE THREAD

**Issue by LaraHCroft91** [TokyoSU/Plugin_TokyoSU#9]
He turns his torso up and down like he is looking up and then bending forward. He does it anytime and often. Probably has to do something with #5

**Comment by TokyoSU** [comment]
the yeti is fixed, so it's the baddy one, i will fix it in the future update :)

**Comment by TokyoSU** [comment]
fixed for the next update :)

**Comment by LaraHCroft91** [comment]
Confirmed.
